name: .NET Project Build

on:
    push:
        paths:
            - DotNET/**

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Repository
              uses: actions/checkout@v4

            - name: Setup .NET
              uses: actions/setup-dotnet@v3
              with:
                dotnet-version: |
                  9.0.*
                  8.0.*

            - name: Restore Dependencies
              run: dotnet restore DotNET

            - name: Build Solution
              run: dotnet build DotNET --configuration Release --no-restore

            - name: Run Tests
              run: dotnet test DotNET --configuration Release --no-build --verbosity normal