name: GitHub Credentials Merge Actions

on:
    push:
        branches: ['linux']

permissions:
  contents: write

jobs:
  push:
    runs-on: ubuntu-latest
    steps:
        - name: Checkout Branch
          uses: actions/checkout@v4
          with: 
            fetch-depth: 0
        
        - name: Configure Git
          run: |
            git config user.name "GEONWOO CHOI"
            git config user.email "geonwoo8873@outlook.kr"

        - name: Merge into main
          run: |
            git fetch origin main linux
            # git checkout -B main origin/main
            git checkout main
            # git merge --allow-unrelated-histories --no-ff --no-edit origin/linux
            git merge --no-ff --no-edit origin/linux
            git push origin main